server.port=8080
server.address=0.0.0.0
server.forward-headers-strategy=framework

# --- CẤU HÌNH KẾT NỐI POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.bgmwwohtvcpfpwzhkbkx
spring.datasource.password=ft73#xYy/p5C!*X
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate (tự động tạo bảng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tắt các log SQL chi tiết để làm sạch Terminal
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# --- CẤU HÌNH MAIL GỬI MÃ XÁC THỰC ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=clonegmail0@gmail.com
spring.mail.password=uwlrsvkdrvuhneen

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAUTH2 GOOGLE CONFIG (TODO: Thay ID và SECRET thật từ Google Cloud Console)
spring.security.oauth2.client.registration.google.client-id=948171219937-bgn4oou0kv5pffq7bli1nem8568gro1n.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Khóa bí mật cho JWT (Phải dài ít nhất 64 ký tự cho HS512)
jwt.secret=LC_Network_PBL5_Secret_Key_Super_Secure_Must_Be_At_Least_64_Bytes_Long_To_Be_Valid

# Jackson: serialize LocalDate thành chuỗi "YYYY-MM-DD" thay vì array
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# Cấu hình kích thước file tải lên
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# --- CẤU HÌNH CLOUDINARY (LƯU ẢNH TRÊN MÂY) ---
cloudinary.cloud_name=dptmicerz
cloudinary.api_key=671395917458997
cloudinary.api_secret=ncKAQqdmY9Ex3B5AVT20Emkh7ag
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
